[project]
name = "analysis"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.3",
    "igraph>=1.0.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
]
